### ISSUE TITLE
login error on MindLogger Web

### ISSUE THREAD

**Issue by sanuann** [ChildMindInstitute/mindlogger-web#43] opened 2019-06-11 19:43 UTC
I get this message on login:

Oh no! TypeError: Cannot convert undefined or null to object

Please file an issue on GitHub so we can fix this problem!

5c47d89bdedfea6af140e70c

**Comment by WorldImpex** [comment] 2020-01-19 13:37
@binarybottle Do you remember this error? I wonder if it is reproducible any longer

**Comment by binarybottle** [comment] 2020-01-19 14:24
I don't remember, and never ran into it myself.

**Comment by shnizzedy** [comment] 2020-01-20 15:38
I just added a blocker ― this issue is for MindLogger web, which has not been functional since the massive schema changes in October.

**Comment by WorldImpex** [comment] 2020-05-18 15:26
Deprecated since we are moving to react

**Closed by WorldImpex** 2020-05-18 15:26 UTC
Labels: JavaScript, Vue, bug, critical for web app users, mindloggerweb, unknown scope, web app
